### ISSUE TITLE
Add batch 25 students portfolio URLs

### ISSUE THREAD

**Issue by cveneziani** [lewagon/amsterdam#7]
## TODO
- [x] Replace robot by real mugshots of students
- [x] Replace mugshots overview here [source/images/mugshots/batch-25.jpg](https://github.com/lewagon/amsterdam/blob/1ab33deb34f09458d1e02800db34276426f7aebb/source/images/mugshots/batch-25.jpg)
- [x] Add URLs of students portfolios

**Comment by cveneziani** [comment]
See PR #9
